# chwb2
# Autogenerated from man page /usr/share/man/man1/chwb2.1.gz
complete -c chwb2 -s I --description '.'
complete -c chwb2 -s O --description 'Set the inner/outer border color of wid to color.'
complete -c chwb2 -s i --description '.'
complete -c chwb2 -s o --description 'Sets the inner/outer border width of wid to size.'

