# dmenu
# Autogenerated from man page /usr/share/man/man1/dmenu.1.gz
complete -c dmenu -s b --description 'dmenu appears at the bottom of the screen.'
complete -c dmenu -s f --description 'dmenu grabs the keyboard before reading stdin if not reading from a tty.'
complete -c dmenu -s i --description 'dmenu matches menu items case insensitively.'
complete -c dmenu -s l --description 'dmenu lists items vertically, with the given number of lines.'
complete -c dmenu -s h --description 'dmenu uses a menu line of at least \'height\' pixels tall, but no less than 8.'
complete -c dmenu -s x --description 'dmenu is placed at this offset measured from the left side of the monitor.'
complete -c dmenu -s y --description 'dmenu is placed at this offset measured from the top of the monitor.'
complete -c dmenu -s w --description 'sets the width of the dmenu window.'
complete -c dmenu -s m --description 'dmenu is displayed on the monitor number supplied.'
complete -c dmenu -s p --description 'defines the prompt to be displayed to the left of the input field.'
complete -c dmenu -o fn --description 'defines the font or font set used.'
complete -c dmenu -o nb --description 'defines the normal background color.'
complete -c dmenu -o nf --description 'defines the normal foreground color.'
complete -c dmenu -o sb --description 'defines the selected background color.'
complete -c dmenu -o sf --description 'defines the selected foreground color.'
complete -c dmenu -s v --description 'prints version information to stdout, then exits.'

