# persist-tool
# Autogenerated from man page /usr/share/man/man1/persist-tool.1.gz
complete -c persist-tool -l help -s '?' --description '.'
complete -c persist-tool -l output-dir -s o --description '.'

