# slogencrypt
# Autogenerated from man page /usr/share/man/man1/slogencrypt.1.gz
complete -c slogencrypt -l key-file -s k --description 'The current host key from the system where the encryption will be performed.'
complete -c slogencrypt -l mac-file -s m --description 'The current MAC file from the system where the encryption will be performed.'
complete -c slogencrypt -l help -s h --description 'Display a help message.'

