# slogverify
# Autogenerated from man page /usr/share/man/man1/slogverify.1.gz
complete -c slogverify -l iterative -s i --description 'Iterative mode.'
complete -c slogverify -l key-file -s k --description 'The initial host key (k0).  This option is used in normal mode only.'
complete -c slogverify -l mac-file -s m --description 'The current MAC file used.'
complete -c slogverify -l prev-key-file -s p --description 'The host key corresponding to the previous log file.'
complete -c slogverify -l prev-mac-file -s r --description 'The MAC file from the previous log file.'
complete -c slogverify -l help -s h --description 'Display a help message.'

