# slogkey
# Autogenerated from man page /usr/share/man/man1/slogkey.1.gz
complete -c slogkey -l master-key -s m --description 'Generates a mew master key.'
complete -c slogkey -l derive-key -s d --description 'Derive a host key using a previously generated master key.'
complete -c slogkey -l counter -s c --description 'Display the current log sequence counter of a key.'
complete -c slogkey -l help -s h --description 'Display a help message.'

