# wew
# Autogenerated from man page /usr/share/man/man1/wew.1.gz
complete -c wew -s l --description 'List event mask values.'
complete -c wew -s m --description 'Set event mask to mask (defaults to XCB_EVENT_MASK_ENTER_NOTIFY) El EVENT VAL…'

